Repository blacksmoke26/pr-sandbox, pull requests merged in 2021-08, with the labels that each got.

#1 Added usama file
  usama.js
Labels: enhancement

#2 added processInfo method to process info in realtime
  Fahad.kt
Labels: enhancement, good first issue

#3 Helper Class
  Helper.swift
Labels: bug, documentation
